on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:
    inputs:
      tag:
        description: "Select the release tag"
        required: true
        default: "v0.0.1"

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Setup pnpm
        uses: pnpm/action-setup@v6
        with:
          version: 11
          run_install: false
          cache: true
      - name: Install dependencies
        run: pnpm install
      - name: Build
        run: pnpm run zip & pnpm run zip:firefox
      - name: Upload Release Assets
        uses: softprops/action-gh-release@v3
        with:
          files: |
            .output/*.zip
          generate_release_notes: true
          tag_name: ${{ github.event.inputs.tag || github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
